streatham_go/accounts/urls.py
from django.urls import path

from . import views

# set the app name
app_name = 'accounts'
# create a list of url patterns
urlpatterns = [
    # register page
    path('register/', views.register, name='register'),
    # login page
    path('login/', views.login_view, name='login'),
    # logout page
    path('logout/', views.logout_view, name='logout'),
    # search page
    path('search/', views.search, name='search'),
    # profile page
    path('profile/<username>/', views.profile, name='profile'),
    # add friend page
    path('profile/<username>/add', views.add, name='add'),
    # activate user page
    path('<username>/activate/', views.activate, name='activate'),
    # add xp path
    path('<username>/xp', views.xp, name='xp'),
]

streatham_go/app/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

# set the app name
app_name = 'app'
# create a list of url patterns
urlpatterns = [
    # home page
    path('home/', views.home, name='home'),
    # leaderboard page
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    # ladning page
    path('', views.index, name='index'),
    # play page
    path('play/<token>', views.play, name='play'),
    # conversation javascript (this needs to be rendered)
    path('app/conversion.js', views.conversation, name='conversation'),
    # play javascript (this needs to be rendered)
    path('app/play.js', views.play_js, name='play_js'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# also add the static files to the url patterns

streatham_go/streatham_go/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include('app.urls')),
    path("accounts/", include('accounts.urls')),
    path("admin/", admin.site.urls),
]

# Let Django serve media files in debug mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

streatham_go/app/views/home.py
from django.conf import settings
from django.shortcuts import render, redirect
from app.models import Location, Game, Word
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core import serializers
from ..tokens import generate_game_jwt
from app.models import Leaderboard


@login_required
def home(request):
    # initalize the context variable
    context = {}

    # check if the method is post
    if request.method == 'POST':
        # get the building name from the form
        buildingName = request.POST.get('building')
        # generate the game token
        # get user leaderbaord entry
        leaderboard_entry = Leaderboard.objects.get(user=request.user)
        token = generate_game_jwt(request.user, leaderboard_entry.xp,
                                  leaderboard_entry.level, buildingName)

        # redirect to the play page with the token
        return redirect('app:play', token=token)

    # check if there are any locations in the database
    if Location.objects.count() == 0:
        # if there are no locations, set the error message
        messages.error(request, ("Found no locations in database. "
                                 "Please add some locations in the "
                                 "admin panel."))
    else:
        # if there are locations, get the locations from the database
        num_games = Game.objects.count()
        word_data = Word.objects.all()
        words = Word.get_words(word_data)
        facts = []
        for word in words:
            facts.append(word['fact'])
        # Get all games from the model
        games_model = Game.objects.all()
        games = [game.name for game in games_model]

        locations = serializers.serialize("json", Location.objects.all())
        # set the context variable
        context = {
            'locations': locations,
            'num_games': num_games,
            'games': games,
            'facts': facts,
            'GOOGLE_API_KEY': settings.GOOGLE_API_KEY,
        }

    # render the home page
    return render(request, 'app/home.html', context)

streatham_go/app/views/leaderboard.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from ..models import Leaderboard


@login_required
def leaderboard(request):
    # Get the leaderboard data sorted by level then xp,
    leaderboard_data = Leaderboard.objects.order_by('-level', '-xp')

    # Get the user data from the leaderboard data
    user_data = Leaderboard.get_user_data(leaderboard_data)
    user_data = sorted(user_data,
                       key=lambda x: (x['level'], x['xp']), reverse=True)

    # Find the current user's leaderboard data and rank
    current_user_data = Leaderboard.get_current_user_data(
        request.user, leaderboard_data)
    current_user_rank = Leaderboard.get_current_user_rank(
        request.user, user_data, current_user_data)

    context = {
        'globalLeaderboard': leaderboard_data,
        'user_data': user_data,
        'current_user_data': current_user_data,
        'current_user_rank': current_user_rank
    }

    return render(request, 'app/leaderboard.html', context)

streatham_go/app/views/play.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from ..models import Location, Word
from ..tokens import validate_game_jwt


# add the login required decorator
@login_required
def play(request, token):
    # initalize the context variable
    context = {}

    # get the words data

    word_data = Word.objects.all()

    words = Word.get_words(word_data)

    # get the building name from the token
    buildingName = validate_game_jwt(request, token)
    # validate the token
    if buildingName is None:
        # if the toekn is invalid, set the error message
        context['error'] = "Invalid token"
    else:
        # get the building from the database
        building = Location.objects.filter(name=buildingName).first()
        # get the game data from the building
        game_data = render_to_string('app/' + building.game.file)

        # set the context variables
        context['building_name'] = buildingName
        context['game_content'] = game_data
        context['words'] = words

    # render the play page
    return render(request, 'app/play.html', context)


@login_required
def play_js(request):
    return render(request, 'app/play.js',
                  content_type='application/javascript')

streatham_go/app/templates/app/crossword.html
{% load static %}
<link rel="stylesheet" href="{% static 'app/crossword.css' %}">

<div id="crossword-container">
    <table id="crossword-grid"></table>
</div>
<div id="crossword-buttons">
    <button id="crossword-check" onClick="checkGrid()">Check</button>
    <button id="crossword-solve" onClick="solveGrid()">Solve</button>
    <button id="crossword-reset" onClick="clearGrid()">Clear</button>
</div>
<div id="crossword-score">
    <h3>Score: <span id="crossword-score-value">0</span></h3>
</div>
<div id="crossword-hints">
    <div id="crossword-hints">
        <div id="crossword-hints-across" class="d-flex flex-column overflow-auto">
            <h3>Across:</h3>
        </div>
        <div id="crossword-hints-down" class="d-flex flex-column overflow-auto">
            <h3>Down:</h3>
        </div>
    </div>
</div>
<script src="{% static 'app/crossword.js' %}"></script>

streatham_go/app/templates/app/hangman.html
{% load static %}
<link rel="stylesheet" href="{% static 'app/hangman.css' %}">

<h1>Hangman</h1>
<p>Guess some letters!</p>
<div class="interface-container">
    <svg height="240" width="180" class="person-container">
        <!-- Head -->
        <circle cx="140" cy="70" r="20" class="person-part" />
        <!-- Body -->
        <line x1="140" y1="90" x2="140" y2="150" class="person-part" />
        <!-- Arms -->
        <line x1="140" y1="120" x2="120" y2="100" class="person-part" />
        <line x1="140" y1="120" x2="160" y2="100" class="person-part" />
        <!-- Legs -->
        <line x1="140" y1="150" x2="120" y2="180" class="person-part" />
        <line x1="140" y1="150" x2="160" y2="180" class="person-part" />
        <!-- Frame -->
        <line x1="60" y1="20" x2="140" y2="20" />
        <line x1="140" y1="20" x2="140" y2="50" />
        <line x1="60" y1="20" x2="60" y2="230" />
        <line x1="20" y1="230" x2="100" y2="230" />
    </svg>
</div>
<div class="word" id="word"></div>

<!-- Container for final message -->
<div class="message-container" id="message-container">
    <div class="popup">
        <h2 id="final-message"></h2>
        <button id="play-button">Play Again</button>
    </div>
</div>

<!-- Notification -->
<div class="notification-container" id="notification-container">
    <p>You have already entered this letter</p>
</div>

<script src="{% static 'app/hangman.js' %}"></script>

streatham_go/app/templates/app/home.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'app/home.css' %}" />

{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% else %}
  {% if debug %}
  <script>
    var debug = true
  </script>
  {% else %}
  <script>
  var debug = false
  </script>
  {% endif %}


<script>  
  var facts = {{ facts|safe}}
  var num_games = {{ num_games }}
  function getColorAtIndex(x) {
    const step = 360 / num_games;
    const hue = x * step;
    const saturation = 100;
    const lightness = 80;
    const rgb = hslToRgb(hue, saturation, lightness);
    return rgb;
  }

  function hslToRgb(h, s, l) {
    h /= 360;
    s /= 100;
    l /= 100;
    let r, g, b;
    if (s === 0) {
      r = g = b = l;
    } else {
      const hue2rgb = (p, q, t) => {
        if (t < 0) t += 1;
        if (t > 1) t -= 1;
        if (t < 1 / 6) return p + (q - p) * 6 * t;
        if (t < 1 / 2) return q;
        if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
        return p;
      };
      const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
      const p = 2 * l - q;
      r = Math.round(hue2rgb(p, q, h + 1 / 3)*255);
      g = Math.round(hue2rgb(p, q, h)*255);
      b = Math.round(hue2rgb(p, q, h - 1 / 3)*255);
    }
    return `rgb(${r}, ${g}, ${b})`;
  }
  var games = {{ games|safe }};
  var keyMessage = "";
  for (var i = 0; i < games.length; i++){
    // set color of game
    // append game to key message as a list item
    keyMessage += "<span style='color: " + getColorAtIndex(i) + "'>" + games[i]
    if (i < games.length - 1){
      keyMessage += ", </span> "
    }
    else{
      keyMessage += ". </span>"
    }
  }
</script>

<body>
  <div class="text-center text-white border-bottom"> <h1 class="display-1 align-middle" >  Find Your QuestGiver
  </h1></div>
  <br>
      <h5 class="card-title"> </h5>
      <div id="googleMap" style="height:50vh;transform-origin:top;transform:scale(0.95);">
      <script>
        // Generate google map
        var locations = '{{ locations|escapejs }}'
        locations = JSON.parse(locations)
          // Return the interpolated color
        function myMap() {
          boundsNorth = 50.740400
          boundsSouth = 50.730000
          boundsEast = -3.524000
          boundsWest = -3.542700


          var mapProp = {
            // center it on forum
            scrollwheel: false, 
            disableDoubleClickZoom: true,
            center: new google.maps.LatLng(50.735344013066786,-3.533710030939591),
            restriction: {
              latLngBounds: {
                north: boundsNorth,
                south: boundsSouth,
                east: boundsEast,
                west: boundsWest,
              },
              strictBounds: false,
            },
            disableDefaultUI: true,
            zoom:17,
            minZoom: 17,
            maxZoom: 20,
            mapId: "27c6b9a1bc6d90d5"
          };
          var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);

          // If click on map, clear dialogue screens!
          map.addListener("click", () => {
            keyScene();
          });
          for (let i = 0; i < locations.length; i++) {
            building = locations[i].fields
            var iconMarker = {
              url: "/media/" + (building.icon),
              labelOrigin: new google.maps.Point(20,-10),
              scaledSize: new google.maps.Size(40, 40)
            }
            var labelMarker = {
              text: (building.name),
              color: getColorAtIndex(building.game-1),
              fontFamily: "Courier New",
              className: "maplabel",
            }
            
            var positionMarker = {
              lat: Number(building.latitude),
              lng: Number(building.longitude)
            }
            var marker = new google.maps.Marker({position: positionMarker, label: labelMarker, icon: iconMarker, animation:google.maps.Animation.DROP});
            marker.setMap(map);
            google.maps.event.addListener(marker, 'click', function() {
              // unfortunately, this is the only way to reference the correct building
              // would rather pass the building object to the clickHandler, but it gets
              // overwritten by the loop
              clickHandler(i, map)
            });
          };
        };
        function clickHandler(i, map) {
          building = locations[i].fields

          buildingPos = {
              lat: Number(building.latitude),
              lng: Number(building.longitude)
            }
          map.panTo(buildingPos);
          // set icon of who is talking
          buildingSetter(building)
          updateIcon(building.icon)
          welcomeScene()
          // set dialogue
        }
        </script>



      <script
        src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_API_KEY }}&callback=myMap"
      ></script>
      </div>
  
  <div id="key"></div>
  <div id="talking">
    <div class="container-fluid">
        <div class="row g-2 form-group">
            <div class="col-3 col-lg-1 mx-auto" id ="icon" style="image-rendering: pixelated">
            </div>
            <div class="col" id="dialogue">
            </div>
        </div>
    </div>
  </div>
  <div class="bottom" style="text-align: center; ">
    <div id="buttons" class="btn-group mr-2 rounded-0" role="group" aria-label="First group">
    </div>
  </div>
  <br>

</body>
<script src=" {% url 'app:conversation' %} "></script>

{% endif %}

{% endblock %}

streatham_go/app/templates/app/index.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}{% bootstrap_messages %}

<DOCTYPE! html>
<html lang="en">

{% load static %}
<base href="/">
<link rel="stylesheet" href="{% static 'app/index.css' %}">
    <body>
        <div class="text-center text-white border-bottom">        <h1 class="display-1 align-middle" >StreathamQuest</h1></div>
        <br>
        <div class = "container">
            <div class = "row">
            <div class = "col-12 col-lg-5 mx-auto">
                <div id="carouselExampleIndicators" class="carousel slide">
                    <div class="carousel-indicators">
                      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 3"></button>
                      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4" aria-label="Slide 3"></button>
                    </div>
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img src="{% static 'app/homepage.png'%}" class="d-block w-100 h-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="{% static 'app/trivia.png'%}" class="d-block w-100 h-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="{% static 'app/crossword.png'%}" class="d-block w-100 h-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="{% static 'app/wordsearch.png'%}" class="d-block w-100 h-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="{% static 'app/tictactoe.png'%}" class="d-block w-100 h-100" alt="...">
                      </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                  </div>
            </div>
            <div class="col">
                    <p> 
                        A slow creeping force is threatening the townsfolk of Streatham. Known as <b>Pollutonia</b>, a deadly magic feeding off the ignorance of common people. Ward off the Pollutonia by completing quests.
                    </p>
                    <h2 class="header">
                        It Feeds On Ignorance.
                    </h2>
                    <br>
                    {% if not user.is_authenticated %}
                    <a href="{% url 'accounts:login' %}" class="btn btn-info rounded-0" role="button">
                      LOGIN
                    </a>
                    <a href="{% url 'accounts:register' %}" class="btn btn-info rounded-0" role="button">
                        REGISTER
                    </a>
                    {% else %}
                    <a href="{% url 'app:home' %}" class="btn btn-info rounded-0" role="button">
                      PLAY NOW
                    </a>
                    {% endif %}
            </div>
        </div>
        </div>
    </body>
</html>
{% endblock %}

streatham_go/app/templates/app/leaderboard.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'app/leaderboard.css' %}">

<body>
    <div class="text-center text-white border-bottom">
        <h1 class="display-1 align-middle">Leaderboard</h1>
    </div>
    <br>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Username</th>
                    <th>Level</th>
                    <th>XP</th>
                    <th>Games Played</th>
                </tr>
            </thead>
            <tbody>
                <!-- Loops through the top 10 users in the leaderboard -->
                {% for u in user_data|slice:":10" %}
                <!-- If row is for logged in user, apply currentUserRow class -->
                {% if u.username == current_user_data.user.username %}
                <tr class="currentUserRow">
                    {% else %}
                    <tr>
                        {% endif %}
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'accounts:profile' u.username %}">
                        {{u.username }}
                    </a></td>
                        <td>{{ u.level }}</td>
                        <td>{{ u.xp }}</td>
                        <td>{{ u.numGamesPlayed }}</td>
                    </tr>
                    {% endfor %}
                    <!-- If user is not in top 10, include an extra row with their details-->
                    {% if current_user_rank > 10 %}
                    <tr class="currentUserRow">
                        <td>{{ current_user_rank }}</td>
                        <td><a href="{% url 'accounts:profile' current_user_data.user.username %}">
                        {{ current_user_data.user.username }}
                    </a></td>
                        <td>{{ current_user_data.level }}</td>
                        <td>{{ current_user_data.xp }}</td>
                        <td>{{ current_user_data.numGamesPlayed }}</td>
                    </tr>
                    {% endif %}
            </tbody>
        </table>
    </div>
</body>
{% endblock %}

streatham_go/app/templates/app/play.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %} {%load static %}

{% if error %}
<div class="text-center text-white border-bottom">
    <h1 class="display-1 align-middle" >
        {{error}}
    </h1>
</div>
<center>
    <p class="mt-2 h3">
        The token you gave is invalid or has expired. Please try again.
    </p>
        <a href="{% url 'app:home' %}" class="mt-2 btn btn-primary">Back to Home</a>
</center>
{% else %}
<div class="text-center text-white border-bottom">
    <h1 class="display-1 align-middle" >
        {{building_name}}
    </h1>
</div>

<script>
    var userWon = false;
    const words = {{ words|safe}};
</script>

{{game_content|safe}}

<script src="{% url 'app:play_js' %}"></script>

{% endif %}


{% endblock %}

streatham_go/app/templates/app/tictactoe.html
{% load static %}
<link rel="stylesheet" href="{% static 'app/tictactoe.css' %}">
<div id="container">
    <h2>Beat the Pollutonia in 3 rounds!</h2>
    <h2 id="playerTurn">Turn: You</h2>
    <h2 id="score">Score: 0-0</h2>
    <div id="grid">
        <div class="row">
            <div class="cell" id="cell1" onClick="replyToClick(this.id)"></div>
            <div class="cell" id="cell2" onClick="replyToClick(this.id)"></div>
            <div class="cell" id="cell3" onClick="replyToClick(this.id)"></div>
        </div>
        <div class="row">
            <div class="cell" id="cell4" onClick="replyToClick(this.id)"></div>
            <div class="cell" id="cell5" onClick="replyToClick(this.id)"></div>
            <div class="cell" id="cell6" onClick="replyToClick(this.id)"></div>
        </div>
        <div class="row">
            <div class="cell" id="cell7" onClick="replyToClick(this.id)"></div>
            <div class="cell" id="cell8" onClick="replyToClick(this.id)"></div>
            <div class="cell" id="cell9" onClick="replyToClick(this.id)"></div>
        </div>
    </div>
    <button id="restart" onClick="restartGame()">Next round!</button>
</div>
<script src="{% static 'app/tictactoe.js' %}"></script>

streatham_go/app/templates/app/trivia.html
{% load static %}

<link rel="stylesheet" href="{% static 'app/trivia.css' %}">
<link href="https://fonts.cdnfonts.com/css/so-bad" rel="stylesheet">

<div id="home-container">
    <div id="home" class="flex-column flex-center">
        <h1>Trivia Quest</h1>
        <h2>Are you ready?</h2>
        <a class="btn" id="homeBtn" onClick="toGamePage(this.id)">
            Start
        </a>
    </div>
</div>

<div id="game-container">
    <div id="game" class="flex-column flex-center">
        <div class="hud">
            <div class="hud-item">
                <h1 class="title">
                    Trivia Quest
                </h1>
            </div>
            <div class="hud-item">
                <h2 id="score">Score: 0</h2>
            </div>
            <div class="hud-item">
                <p id="progressText" class="hud-prefix">
                    Question
                </p>
                <div id="progressBar">
                    <div id="progressBarFull"></div>
                </div>
            </div>
        </div>
        <h1 class="question" id="question">
            Answer this question
        </h1>
        <div class="flex-center">
            <div class="choice-container" id="btna" onClick="replyToClick(this.id)">
                <p class="choice-prefix">
                    A.
                </p>
                <p class="choice-text" data-letter="a">
                    Choice A
                </p>
            </div>
            <div class="choice-container" id="btnb" onClick="replyToClick(this.id)">
                <p class="choice-prefix">
                    B.
                </p>
                <p class="choice-text" data-letter="b">
                    Choice B
                </p>
            </div>
            <div class="choice-container" id="btnc" onClick="replyToClick(this.id)">
                <p class="choice-prefix">
                    C.
                </p>
                <p class="choice-text" data-letter="c">
                    Choice C
                </p>
            </div>
            <div class="choice-container" id="btnd" onClick="replyToClick(this.id)">
                <p class="choice-prefix">
                    D.
                </p>
                <p class="choice-text" data-letter="d">
                    Choice D
                </p>
            </div>
        </div>
    </div>
</div>

<div id="end-win-container">
    <div class="flex-column flex-center">
        <h1>
            Your Final Score is:
        </h1>
        <h2 id="final-score-win">
            0
        </h2>
        <h1>
            Well Done! You have completed this quest!
            I shall have another quest for you tomorrow!
        </h1>
        <a class="btn" id="endBtn" href="{% url 'app:home' %}">
            Back To Home Page
        </a>
    </div>
</div>

<div id="end-lose-container">
    <div class="flex-column flex-center">
        <h1>
            Your Final Score is:
        </h1>
        <h2 id="final-score-lose">
            0
        </h2>
        <h1>
            Unlucky traveller, you have failed this quest!
            Please come by again tomorrow to have another go!
        </h1>
        <a class="btn" id="endBtn" href="{% url 'app:home' %}">
            Back To Home Page
        </a>
    </div>
</div>

<script src="{% static 'app/trivia.js' %}"></script>

streatham_go/app/templates/app/wordsearch.html
{% load static %}
<link rel="stylesheet" href="{% static 'app/wordsearch.css' %}">
<!DOCTYPE html>
<html>
  <head>
    <style>
      td {
        border: 1px solid black;
        width: 40px;
        height: 40px;
        text-align: center;
      }
      word-search-container{ 
        margin-top: 10px;
      }
    </style>
  </head>
  <body>
  
    <div id="game-container">
      <div id="word-search-container">
      </div>
      <p id="timer"></p>
      <div id="words"></div>
    </div>

    <div id="win-container">
      <h1 id= "win-text">
        Nicely done old friend. Feel free to play again!
      </h1>
    </div>

    <div id="lose-container">
      <h1 id= "lose-text">
        Unlucky traveller... You haven't succeeded this time...
      </h1>
    </div>

    <script src=" {% static 'app\wordsearch.js' %} "></script>
  </body>
</html>