streatham_go/accounts/urls.py
from django.urls import path

from . import views

# set the app name
app_name = 'accounts'
# create a list of url patterns
urlpatterns = [
    # register page
    path('register/', views.register, name='register'),
    # login page
    path('login/', views.login_view, name='login'),
    # logout page
    path('logout/', views.logout_view, name='logout'),
    # search page
    path('search/', views.search, name='search'),
    # profile page
    path('profile/<username>/', views.profile, name='profile'),
    # add friend page
    path('profile/<username>/add', views.add, name='add'),
    # activate user page
    path('<username>/activate/', views.activate, name='activate'),
    # add xp path
    path('<username>/xp', views.xp, name='xp'),
]

streatham_go/app/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

# set the app name
app_name = 'app'
# create a list of url patterns
urlpatterns = [
    # home page
    path('home/', views.home, name='home'),
    # leaderboard page
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    # ladning page
    path('', views.index, name='index'),
    # play page
    path('play/<token>', views.play, name='play'),
    # conversation javascript (this needs to be rendered)
    path('app/conversion.js', views.conversation, name='conversation'),
    # play javascript (this needs to be rendered)
    path('app/play.js', views.play_js, name='play_js'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# also add the static files to the url patterns

streatham_go/streatham_go/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include('app.urls')),
    path("accounts/", include('accounts.urls')),
    path("admin/", admin.site.urls),
]

# Let Django serve media files in debug mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

streatham_go/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <link href="https://fonts.cdnfonts.com/css/so-bad" rel="stylesheet">
    <link href="https://fonts.cdnfonts.com/css/merchant-copy-doublesize" rel="stylesheet">
    <link href="https://fonts.cdnfonts.com/css/mairon" rel="stylesheet">
        <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" /> {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %} {% bootstrap_messages %}
        <title>StreathamQuest</title>
        <style>
            body {
                height: 100%;
                background-color: #6d604e;
                font-family: 'So Wide', sans-serif;
                color: black;
            }

            h1 {
                padding-top: 20px;
                font-family: 'So Bad', sans-serif;
            }

            
            h2 {
                font-family: 'Mairon', sans-serif;
                font-family: 'So Bad', sans-serif;                               
            }
            
            .navbar {
                padding-top: 0;
                padding-bottom: 0;
            }
            
            .nav-link {
                padding: 15px;
            }
            
            ul.nav li a {
                color: #fff;
                padding: 15px;
            }
            
            ul li a.nav-link:not(.home):hover {
                background-color: #958A6E;
                color: #fff;
                transition: 0.5s;
            }
            
            ul li a.nav-link.active {
                background-color: #958A6E;
                color: #fff;
            }
            
            .border-right {
                border-right: 1px solid #110d08;
            }
            
            .container-fluid {
                padding-right: 0px;
            }
            
            .navbar-collapse {
                display: flex;
                flex-wrap: nowrap;
            }
            
            a.navbar-brand {
                font-size: 25px;
                color: #fff;
            }
        </style>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #40382d;">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">SQ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav me-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link border-right {% if 'home' in request.path %}active{% endif %}" aria-current="page" href="{% url 'app:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link border-right {% if 'leaderboard' in request.path %}active{% endif %}" aria-current="page" href="{% url 'app:leaderboard' %}">Leaderboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if 'search' in request.path %}active{% endif %}" aria-current="page" href="{% url 'accounts:search' %}">Search</a>
                        </li>
                        {% endif %}
                    </ul>
                    <ul class="nav ml-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link border-right {% if 'profile' in request.path %}active{% endif %}" aria-current="page" href="{% url 'accounts:profile' user.username %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link border-right {% if 'login' in request.path %}active{% endif %}" aria-current="page" href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if 'register' in request.path %}active{% endif %}" aria-current="page" href="{% url 'accounts:register' %}">Register</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            {% block content %} {% endblock content %}
        </div>

    </body>

</html>